jobs:
  build-and-push-image:
    permissions:
      contents: read
      packages: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Log in to the container registry
      uses: docker/login-action@v2
      with:
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        username: ${{ github.actor }}
    - continue-on-error: true
      id: meta
      name: Extract metadata (tags, labels)
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/validator/validator
        tags: type=semver,pattern={{version}}
    - continue-on-error: true
      name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        labels: ${{ steps.meta.outputs.labels }}
        push: false
        tags: ghcr.io/validator/validator:latest, ${{ steps.meta.outputs.tags }}
name: Push a new Docker image
on:
  repository_dispatch:
    types: trigger-ga___docker-push.yml
